name: "Hello"

on:
  pull_request:
    types: [opened, reopened]
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: "needs-review"

    - name: Install Apidog CLI
      run: npm install -g apidog-cli

    - name: Running Test Scenario
      run: apidog run https://api.apidog.com/api/v1/projects/489216/api-test/ci-config/351108/detail?token=xOAFD-YO70LPy-JzZr6WTy -r html,cli